config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  
  resources :articles do
    resources :comments
    resources :attachments
  end

  resources :tags
  resources :authors
  
  resources :author_sessions, only: [:new, :create, :destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}, format: { with: /\A[a-zA-Z]+\z/, message: "Only alphabets" }

  belongs_to :author

  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :attachments, dependent: :destroy

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(', ')
  end

  def tag_list= (tags_string)
    tag_names = tags_string.split(',').collect{|tag| tag.strip.downcase}.uniq
    new_or_found = tag_names.collect{|name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found
  end

end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :article

  has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png', 'image/png']
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!

  validates_confirmation_of :password, message: "Should match password", if: :password

  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :require_auth, only: [:edit,:destroy]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @author = Author.find(current_user.id)
    @article = @author.articles.new(article_params)
    if @article.save
      @article.author_id = current_user.id
      flash.notice = "Woohoo! '#{@article.title}' entry created!"
      redirect_to article_path(@article)
    else 
      flash.notice = "Please fix the errors"
      render 'new'
    end
  end

  def update
    @author = Author.find(current_user.id)
    @article = @author.articles.new(article_params)
    if @article.update(article_params)
      @article.author_id = @author.id
      flash.notice = "Woohoo! '#{@article.title}' entry edited!"
      redirect_to article_path(@article)
    else 
      flash.notice = "Please fix the errors"
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash.notice = "Place has been deleted"
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end

  def require_login
    unless logged_in?
      flash.notice = "Please log in to proceed"
      redirect_to articles_path
    end
  end

  def require_auth
    @article = Article.find(params[:id])
    unless current_user.id == @article.author_id
      flash.notice = 'You are not authorized for this action'
      redirect_to article_path(@article)
    end
  end

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :require_login
  
  def create
    @article = Article.find(params[:article_id])
    @attachment = @article.attachments.create(attachment_params)
    redirect_to article_path(@article)
  end

  private
  def attachment_params
    params.require(:attachment).permit(:image)
  end

  def require_login
    unless logged_in?
      flash.notice = "Please log in to proceed"
      redirect_to article_path(@article)
    end
  end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      @author = Author.find(current_user.id)
      redirect_back_or_to(articles_path,notice: "Logged in as #{@author.username} successfully")
    else
      flash.now.alert = 'Login failed'
      render action: :new
    end
  end

  def destroy
    logout
    redirect_back_or_to(articles_path,notice: "Logged out")
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :zero_or_authenticated, only: [:new, :create]
  before_action :require_login, except: [:new, :create]
  
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end

    #only allow authenticated users or if there are 0 users befre the new and the create action

    def zero_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end

    def require_login
      unless logged_in?
        flash.notice = "Please log in to proceed"
        redirect_to root_path
      end
    end
      
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, except: [:create]
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:author_name,:body)
  end

  def require_login
    unless logged_in?
      flash.notice = "Please log in to proceed"
      redirect_to article_path(@article)
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_login, only: [:destroy]
  
  def index
    @tags = Tag.all
  end
  
  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash.notice = "Tag has been deleted"
    redirect_to tags_path
  end

  private

  def require_login
    unless logged_in?
      flash.notice = "Please log in to proceed"
      redirect_to tags_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_attachment.html.erb
<div>
  <p>  <%= attachment.image_file_name%> </p> <br>
  <p> <%= image_tag attachment.image.url(:medium) %> </p>
</div>

app/views/articles/_comment.html.erb
<div>
  <h4> Commented by <%= comment.author_name%>
  <p class ='comment'>  <%= comment.body%>

  <p> Commented <%= distance_of_time_in_words(comment.created_at, Time.now)%> ago <p>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true, html: {multipart: true}) do |f|%>

  <ul>
    <% @article.errors.full_messages.each do |error| %>
        <li> <%= error %> </li>
    <% end %>
  </ul>

  <p> 
      <%= f.label :title %><br>
      <%= f.text_field :title%> 
  </p>

  <p> 
      <%= f.label :body %> <br>
      <%= f.text_area :body%>
  </p>

  <p>
    <%= f.label :tag_list%>
    <%= f.text_field :tag_list%>
  </p>

  <p> 
      <%= f.submit %> 
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1> Edit place entry </h1>

<%= render partial: 'form'%>

<h2> Add images </h2>

<%= render partial: 'attachments/form'%>

app/views/articles/index.html.erb
<h1> Blog about travel Destinations </h1>

<ul id = "articles">
  <% @articles.each do |place|%>
    <li> 
      <%author = Author.find(place.author_id)%>
      <%= link_to place.title, article_path(place) %> (<%= author.username %>)
    </li>
  <% end %>
</ul>

<%if logged_in? %>
  <div>
    <%= link_to 'Create new post', new_article_path, class: "new_article" %> 
  </div> 
<%end%>

app/views/articles/new.html.erb
<h1> Create your new place </h1>

<%= render partial: 'form'%>

<h2> Add images </h2>

<%= render partial: 'attachments/form'%>

app/views/articles/show.html.erb
<h1> <%= @article.title %> </h1>

<p> Tags: <% @article.tags.each do |tag|%>
    <%= link_to tag.name, tag_path(tag)%>
    <%end%>
</p>

<div> <%= @article.body%> </div>

<div> 
  <% if @article.attachments.exists? %>
    <h3> Images: </h3>
    <p><%= render partial: 'attachment', collection: @article.attachments%></p>
  <%end%>
</div>


<%if current_user.id == @article.author_id%>
  <p> <%= link_to 'Edit place entry', edit_article_path(@article) %>

  <p> <%= link_to 'Delete place entry', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}%>
<%end%>

<p> <%= link_to 'Back to List of Places', articles_path %> </p>

<h3> Comments (<%=@article.comments.size%>)</h3>

<%= render partial: 'comment', collection: @article.comments %>

<h3> Add a comment </h3>

<%= render partial: 'comments/form' %>

app/views/attachments/_form.html.erb
<% unless @article.id.nil?%>
  <%= form_with(model: [ @article, @article.attachments.build], local: true, html: {multipart: true}) do |a| %>
    <p> 
        <%= a.label :image, 'Add an Image' %> <br />
        <%= a.file_field :image%>
    </p>
    
    <p>
      <%= a.submit%>
    </p>
  <%end%>
<% end %>

app/views/author_sessions/new.html.erb
<h1> User Login </h1>

<%= form_tag author_sessions_path, method: :post do%>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

<div>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username </th>
      <th>Email </th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show ', author %></td>
        <td><%= link_to 'Edit ', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy ', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build], local: true) do |c| %>
  <p>
    <%= c.label :author_name, "Your Name"%> <br>
    <%= c.text_field :author_name%>
  </p>
  <p>
    <%= c.label :body, "Your comment"%> <br>
    <%= c.text_area :body%>
  </p>
  <p>
    <%= c.submit%>
  </p>
<%end%>

app/views/tags/index.html.erb
<h1> List of tags <h1>

<ul>
  <% @tags.each do |tag| %>
  <li> <%= link_to tag.name, tag_path(tag) %> </li>
  <%end%>
</ul>

app/views/tags/show.html.erb
<h1> Places with tag: <%= @tag.name%> <h1>

<ul>
  <% @tag.articles.each do |p| %>
  <li> <%= link_to p.title, article_path(p) %> </li>
  <%end%>
</ul>

<p> <%= link_to 'Show all tags', tags_path %> </p>

<%if logged_in?%>
<p> <%= link_to 'Delete tag', tag_path(@tag), method: :delete, data: {confirm:'Are you sure?'}%>
<%end%>